#Fix Device Trees
FF "SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_EAGLE_EYE" "FALSE"
FF "SEC_FLOATING_FEATURE_SETTINGS_CONFIG_BRAND_NAME" "$MODEL"
FF "SEC_FLOATING_FEATURE_SETTINGS_CONFIG_DEFAULT_FONT_SIZE" "2"
FF "SEC_FLOATING_FEATURE_SETTINGS_CONFIG_DEFAULT_POCKET_MODE" "1"
FF "SEC_FLOATING_FEATURE_SETTINGS_CONFIG_ELECTRIC_RATED_VALUE" "DC 9 V; 2.77 A"
FF "SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME" "siop_x1q_sm8250"

#Add Game driver
OBJECTIVE_BLOBS "system" "stock_blobs/priv-app/GameDriver-SM8250" "priv-app"

#Add Stock Google blobs
OBJECTIVE_BLOBS "product" "stock_blobs/priv-app/HotwordEnrollmentOKGoogleEx2HEXAGON" "priv-app"
OBJECTIVE_BLOBS "product" "stock_blobs/priv-app/HotwordEnrollmentXGoogleEx2HEXAGON" "priv-app"
REMOVE  "product" "priv-app/HotwordEnrollmentXGoogleEx4HEXAGON" -q
REMOVE -q "product" "priv-app/HotwordEnrollmentOKGoogleEx4HEXAGON" 
REMOVE -q "product" "priv-app/HotwordEnrollmentXGoogleEx3HEXAGON" 
REMOVE -q "product" "priv-app/HotwordEnrollmentOKGoogleEx3HEXAGON"

#Add Stock Overlay 
REMOVE -overlay "product" 
OBJECTIVE_BLOBS "product" "stock_blobs/overlay/framework-res__auto_generated_rro_product.apk" "overlay"

#Fix Edge Lighting
LOG_START "Fixing Edge Lighting"
BPROP "system" "ro.factory.model" "SM-G981N"


#Use stock bixby values
FF "SEC_FLOATING_FEATURE_BIXBYVISION_CONFIG_QUICKMEASURE" "10;0.0065;1"
FF "SEC_FLOATING_FEATURE_BIXBY_CONFIG_BARGEIN_FUNCTION" "0"
FF "SEC_FLOATING_FEATURE_BIXBY_CONFIG_BARGEIN_PARAM_MODE" "2"
FF "SEC_FLOATING_FEATURE_BIXBY_CONFIG_CUSTOM_FIRMWARE" "2"
FF "SEC_FLOATING_FEATURE_BIXBY_CONFIG_DSPNS_FUNCTION" "0"
FF "SEC_FLOATING_FEATURE_BIXBY_CONFIG_DSP_BITRATE" "32bit"
FF "SEC_FLOATING_FEATURE_BIXBY_SUPPORT_BIXBYKWD" "TRUE"
FF "SEC_FLOATING_FEATURE_BIXBY_SUPPORT_CUSTOM_WAKEUP" "2"
FF "SEC_FLOATING_FEATURE_BIXBY_SUPPORT_LONG_KEY_SERVICE" "TRUE"

