
# Fix full OneUI6/7 Camera
LOG_START "Fixing Camera Props "
CMDLINE "system" "sed -i '/camera/d' etc/floating_feature.xml"

# Camera Configuration Features
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_ACTION_CLASSIFIER" "1,0"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_HIGH_RESOLUTION_MAX_CAPTURE" "1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_AVATAR_MAX_FACE_NUM" "1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_BOKEH" "-1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_MACRO" "-1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE2" "-1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_BINNING" "-1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_STANDARD_CROP" "-1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_UW" "2"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_WIDE" "0"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_CORE_VERSION" "v2"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_HIGH_RESOLUTION_MAX_CAPTURE" "-1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_LLHDR_PROCESSING_TIMEOUT" "2000"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_MEMORY_USAGE_LEVEL" "3"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_MYFILTER" "1,1,0"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_NIGHT_FRONT_BEAUTY_LEVEL" "2"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_NIGHT_FRONT_DISPLAY_FLASH_TRANSPARENT" "85"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_PERSONALIZATION" "CoolOriWarm"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_QRCODE_INTERVAL" "500"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_STRIDE_OCR_VERSION" "V2"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_UW_DISTORTION_CORRECTION" "0,109,2,19010101,0,0,0,0,0,0"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_VENDOR_LIB_INFO" "beauty.samsung.v4,face_landmark.arcsoft.v2_1,facial_attribute.samsung.v1,super_resolution.arcsoft.v2_1,super_night.mpi.v2,event_detection.samsung.v2,food.samsung.v1,selfie_correction.samsung.v1,mfhdr.arcsoft.v1,llhdr.arcsoft.v1,swuwdc.arcsoft.v1,human_tracking.arcsoft.v2_1,single_bokeh.samsung.v2,human_segmentation.samsung.v2,smart_scan.samsung.v2,dual_bokeh.samsung.v1_1,image_enhance.arcsoft.v1,high_res.arcsoft.v1,localtm.samsung.v1_1,scene_detection.samsung.v1"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_VERSION_FILTER_PROVIDER" "5"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_WIDE_DISTORTION_CORRECTION" "0,0,0,0,0,0,0,0,0,0"
FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_LOGICAL_CAMERA" "false"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_DEFLICKER" "OFF"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_GPPM_SOLUTIONS" "startrail,motionclipper"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_IS_GPPM_1_0_ENABLED" "TRUE"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOIRE_REMOVAL" "OFF"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_SDK_FEATURE_INFO" "version2,super_night,preview_dis,video_hdr,smooth_zoom,logical_rear_camera:camera_id=20"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_SINGLE_PORTRAIT_DISTORTION_CORRECTION" "YUV,DPD"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_SUPERSTEADY_POPUP" "256"
FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_WINE_DETECTOR" "OFF"
FF "SEC_FLOATING_FEATURE_CAMERA_DOCUMENTSCAN_SOLUTIONS" "AI_DEWARPING,SHADOW_REMOVAL,DEBLUR,OBJECT_REMOVAL,COLOR_ENHANCE"
FF "SEC_FLOATING_FEATURE_CAMERA_GRAW_CONFIG_MFP_PIPELINE_MODE" "V3"

    echo "libLttEngine.camera.samsung.so"
} >> "$WORKSPACE/system/system/etc/public.libraries-camera.samsung.txt"

# Related Camera Features (Bixby Vision, Gallery, SAIV)
FF "SEC_FLOATING_FEATURE_BIXBYVISION_CONFIG_QUICKMEASURE" "10;0.0065;1"
FF "SEC_FLOATING_FEATURE_GALLERY_CONFIG_AI_EXPANSION" "AI_Timelapse"
FF "SEC_FLOATING_FEATURE_GALLERY_CONFIG_COLOR_ENGINE_VERSION" "V2"
FF "SEC_FLOATING_FEATURE_GALLERY_CONFIG_FACE_CLUSTER_VERSION" "SRCB_V3"
FF "SEC_FLOATING_FEATURE_GALLERY_CONFIG_IMAGE_TAGGER_UPDATE" "None"
FF "SEC_FLOATING_FEATURE_GALLERY_CONFIG_IMAGE_TAGGER_VERSION" "V516"
FF "SEC_FLOATING_FEATURE_GALLERY_CONFIG_LIVEFOCUS_EFFECT_DUAL_BOKEH" "BLUR,EFFECT,BIGBOKEH,PORTRAIT,RELIGHT,REFOCUS,LIGHT360"
FF "SEC_FLOATING_FEATURE_GALLERY_CONFIG_ZOOM_TYPE" "ZOOM_5K"
FF "SEC_FLOATING_FEATURE_GALLERY_SUPPORT_LOCATION_POI" "TRUE"
FF "SEC_FLOATING_FEATURE_GALLERY_SUPPORT_STORYEDITOR" "4"
FF "SEC_FLOATING_FEATURE_SAIV_CONFIG_AI_REVITAL_VERSION" "1.9,1"
FF "SEC_FLOATING_FEATURE_SAIV_CONFIG_ARDOODLE_LIB" "PET_DETECTION,IMG_PICKING"
FF "SEC_FLOATING_FEATURE_SAIV_CONFIG_MIDAS" "UPSCALE,LOWLIGHT,HDR,DEBLUR,MOIRE,DENOISE_DEBLUR,UPSCALE_DEBLUR,PHOTOPOLISH,SHADOW,REFLECTION,UWDC"
FF "SEC_FLOATING_FEATURE_SAIV_SUPPORT_AI_REVITAL" "TRUE"
FF "SEC_FLOATING_FEATURE_VISION_CONFIG_FACE_DETECTOR_SOLUTION" "SW"
FF "SEC_FLOATING_FEATURE_VISION_CONFIG_IMAGE_CROPPER_VERSION" "V1"
FF "SEC_FLOATING_FEATURE_VISION_CONFIG_RELIGHTING_SOLUTION" "arcsoft.v1"
 
 LOG_START "Fixing Motion Photo | Thanks @ExtremeXT"
 
   FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_VDIS_ON_MOTIONPHOTO" "TRUE"
   FF "SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOTIONPHOTO_CAPTURE_MODE" "[[3,1]]"
   
LOG_START "Adding Extra Features s20 support but was disabled"

    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_VDIS_PORTRAITVIDEO" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_PORTRAIT_INTELLIGENT_OPTIMIZATION_AI_ISP" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_30FPS_ALL_PORTRAITVIDEO" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_4K_PORTRAITVIDEO" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AFSKIP" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AIFRC" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AI_HIGH_RESOLUTION_DRAFT_DOWNSCALE" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_DUAL_PORTRAITVIDEO" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_SEAMLESS_PORTRAITVIDEO" "TRUE"
    FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_SUPER_NIGHT_DRAFT_RAW" "FALSE"
	FF "SEC_FLOATING_FEATURE_CAMERA_SUPPORT_GALLERY_LR" "TRUE"

REMOVE "system" "cameradata/portrait_data"   
OBJECTIVE_BLOBS "system" "camera/cameradata" ""  
LOG_START "Fixing Night Mode crash"
OBJECTIVE_BLOBS "system"  "camera/lib64/libSwIsp_wrapper_v1.camera.samsung.so" "lib64"
OBJECTIVE_BLOBS "system"  "camera/lib64/libSwIsp_core.camera.samsung.so" "lib64"

LOG_START "Fixing Portrait Mode"
BPROP "system" "ro.product.system.name" "$CODENAME"

LOG_START "Fixing Single Take Mode" 

REMOVE "vendor" "etc/singletake"
BLOBS "dm3q" "vendor" "etc/singletake"  

ADD_CONTEXT "vendor" "/vendor/etc/singletake" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/blur_detection" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/blur_detection/BlurDetectionModel_20210527.tflite" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/candid" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/candid/candid.db" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/ClarityScorer" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/ClarityScorer/ClarityScorer.tflite" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing/action172_t0_quantized.tflite" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing/DynamicViewingModelHumanDetection.tflite" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing/FaceEngine_model" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing/FaceEngine_model/FERDetModel.dat" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing/FaceEngine_model/FERTrackModel.dat" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing/movinet_t0.tflite" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/dynamic_viewing/score_model_multi.tflite" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/SmartCrop" "vendor_configs_file"
ADD_CONTEXT "vendor" "/vendor/etc/singletake/SmartCrop/SmartCrop.tflite" "vendor_configs_file"

	REMOVE "vendor"  "saiv/swisp_1.0"
	BLOBS "dm3q" "vendor" "saiv/swisp_1.0/db"
	ADD_CONTEXT "vendor"  "vendor/saiv/swisp_1.0" "vendor_file"

ADD_CONTEXT "vendor"  "vendor/saiv/swisp_1.0/db" "vendor_file"
ADD_CONTEXT "vendor"  "vendor/saiv/swisp_1.0/db/SWISPNet-timestamp" "vendor_file"
ADD_CONTEXT "vendor"  "vendor/saiv/swisp_1.0/db/denoise_model_832x1072x4_0818.pb" "vendor_file"
ADD_CONTEXT "vendor"  "vendor/saiv/swisp_1.0/db/denoise_model_e1275_832X1072X4_v9_1_SD_v1_full.pb" "vendor_file"
ADD_CONTEXT "vendor"  "vendor/saiv/swisp_1.0/db/denoise_model_e734_832x1072x4_PRECONV.pb" "vendor_file"
ADD_CONTEXT "vendor"  "vendor/saiv/swisp_1.0/db/denoise_model_e765_832x1072x4_PRECONV.pb" "vendor_file"

if ! grep -q "Camera End" "$WORKSPACE/vendor/ueventd.rc"; then
    echo -e "\n" >> "$WORKSPACE/vendor/ueventd.rc"
    cat "$OBJECTIVE/camera/ueventd" >> "$WORKSPACE/vendor/ueventd.rc" #Thanks atakaner
fi


COPY_FW "stock" "system" "etc/public.libraries-arcsoft.txt"
COPY_FW "stock" "system" "lib64/libAiSolution_wrapper_v1.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libBright_core.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libFacePreProcessing.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libFaceRestoration.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libFace_Landmark_API.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libFace_Landmark_Engine.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libHprFace_GAE_api.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libHpr_RecFace_dl_v1.0.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libHpr_RecGAE_cvFeature_v1.0.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libHpr_TaskFaceClustering_hierarchical_v1.0.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libImageCropper.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libImageTagger.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libMultiFrameProcessing30.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libMultiFrameProcessing30.snapwrapper.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libMultiFrameProcessing30Tuning.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libMyFilter.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libPortraitDistortionCorrection.arcsoft.so"
COPY_FW "stock" "system" "lib64/libPortraitDistortionCorrectionCali.arcsoft.so"
COPY_FW "stock" "system" "lib64/libUltraWideDistortionCorrection.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libWideDistortionCorrection.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libhigh_dynamic_range.arcsoft.so"
COPY_FW "stock" "system" "lib64/libhigh_res.arcsoft.so"
COPY_FW "stock" "system" "lib64/libhumantracking_util.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libhumantracking.arcsoft.so"
COPY_FW "stock" "system" "lib64/liblow_light_hdr.arcsoft.so"
COPY_FW "stock" "system" "lib64/libsaiv_HprFace_cmh_support_jni.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libsuperresolution.arcsoft.so"
COPY_FW "stock" "system" "lib64/libsuperresolution_wrapper_v2.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libtensorflowLite.dynamic_viewing.camera.samsung.so"
COPY_FW "stock" "system" "lib64/libtensorflowlite_jni_r2.6.so"

